/**
 * CourseCreate 페이지 공통 상수
 */

export const translations = {
  title: { ko: '과정 설계', en: 'Course Design' },
  editTitle: { ko: '과정 수정', en: 'Edit Course' },
  editSubmit: { ko: '수정 완료', en: 'Save Changes' },
  loadTemplate: { ko: '템플릿 불러오기', en: 'Load Template' },
  close: { ko: '닫기', en: 'Close' },
  previous: { ko: '이전', en: 'Previous' },
  next: { ko: '다음', en: 'Next' },
  saveDraft: { ko: '임시저장', en: 'Save Draft' },
  submit: { ko: '강의 등록', en: 'Submit' },
  lastSaved: { ko: '마지막 저장', en: 'Last saved' },
  step1: { ko: '기본 정보', en: 'Basic Info' },
  step2: { ko: '커리큘럼 구성', en: 'Curriculum' },
  step3: { ko: '검토 및 저장', en: 'Review' },
  courseName: { ko: '강의명', en: 'Course Name' },
  courseNamePlaceholder: { ko: '강의명을 입력하세요', en: 'Enter course name' },
  courseDescription: { ko: '강의 설명', en: 'Course Description' },
  courseDescriptionPlaceholder: { ko: '강의에 대한 설명을 입력하세요', en: 'Enter course description' },
  category: { ko: '카테고리', en: 'Category' },
  selectCategory: { ko: '카테고리 선택', en: 'Select category' },
  difficulty: { ko: '난이도', en: 'Difficulty' },
  selectDifficulty: { ko: '난이도 선택', en: 'Select difficulty' },
  courseType: { ko: '유형', en: 'Type' },
  selectType: { ko: '유형 선택', en: 'Select type' },
  online: { ko: '온라인', en: 'Online' },
  offline: { ko: '오프라인', en: 'Offline' },
  blended: { ko: '블렌디드', en: 'Blended' },
  beginner: { ko: '입문', en: 'Beginner' },
  elementary: { ko: '초급', en: 'Elementary' },
  intermediate: { ko: '중급', en: 'Intermediate' },
  advanced: { ko: '고급', en: 'Advanced' },
  startDate: { ko: '시작일', en: 'Start Date' },
  endDate: { ko: '종료일', en: 'End Date' },
  comingSoon: { ko: '준비 중입니다', en: 'Coming Soon' },
  curriculumTitle: { ko: '커리큘럼 구성', en: 'Curriculum' },
  curriculumDesc: { ko: '차시를 추가하고 콘텐츠를 등록하세요. 드래그앤드롭으로 순서를 변경할 수 있습니다.', en: 'Add lessons and register content. Drag and drop to reorder.' },
  noLessons: { ko: '아직 등록된 차시가 없습니다.', en: 'No lessons registered yet.' },
  addFirstLesson: { ko: '첫 번째 차시 추가', en: 'Add First Lesson' },
  addLesson: { ko: '차시 추가', en: 'Add Lesson' },
  lessonTitle: { ko: '차시 제목', en: 'Lesson Title' },
  lessonTitlePlaceholder: { ko: '차시 제목을 입력하세요', en: 'Enter lesson title' },
  lessonDescription: { ko: '차시 설명', en: 'Lesson Description' },
  lessonDescriptionPlaceholder: { ko: '차시에 대한 설명을 입력하세요', en: 'Enter lesson description' },
  contents: { ko: '콘텐츠', en: 'Contents' },
  noContents: { ko: '등록된 콘텐츠가 없습니다.', en: 'No content registered.' },
  fileUpload: { ko: '파일 업로드', en: 'File Upload' },
  externalLink: { ko: '외부 링크', en: 'External Link' },
  loadExisting: { ko: '기존 콘텐츠 불러오기', en: 'Load Existing Content' },
  deleteLesson: { ko: '차시 삭제', en: 'Delete Lesson' },
  reviewTitle: { ko: '과정 설계 검토', en: 'Review Course Design' },
  reviewDesc: { ko: '설계한 과정 정보를 확인하세요. 수정이 필요하면 각 섹션의 수정 버튼을 눌러주세요.', en: 'Please review your course design. Click edit to modify each section.' },
  edit: { ko: '수정', en: 'Edit' },
  basicInfo: { ko: '기본 정보', en: 'Basic Information' },
  tags: { ko: '태그', en: 'Tags' },
  noTags: { ko: '태그 없음', en: 'No tags' },
  period: { ko: '수강 기간', en: 'Course Period' },
  noPeriod: { ko: '기간 미설정', en: 'Not set' },
  multiLanguage: { ko: '다국어 설정', en: 'Multi-language' },
  enabled: { ko: '활성화', en: 'Enabled' },
  disabled: { ko: '비활성화', en: 'Disabled' },
  languageCount: { ko: '개 언어', en: ' languages' },
  curriculum: { ko: '커리큘럼', en: 'Curriculum' },
  totalLessons: { ko: '총 차시', en: 'Total lessons' },
  totalContents: { ko: '총 콘텐츠', en: 'Total contents' },
  lessonNumber: { ko: '차시', en: 'Lesson' },
  contentsCount: { ko: '개 콘텐츠', en: ' contents' },
  noCurriculum: { ko: '등록된 차시가 없습니다.', en: 'No lessons registered.' },
  notEntered: { ko: '미입력', en: 'Not entered' },
  warningTitle: { ko: '입력 확인 필요', en: 'Input Required' },
  warningCourse: { ko: '강의명이 입력되지 않았습니다.', en: 'Course name is required.' },
  warningCategory: { ko: '카테고리가 선택되지 않았습니다.', en: 'Category is required.' },
  warningLesson: { ko: '최소 1개의 차시가 필요합니다.', en: 'At least one lesson is required.' },
  readyToSubmit: { ko: '강의 등록 준비 완료', en: 'Ready to Submit' },
  readyToSubmitDesc: { ko: '모든 필수 정보가 입력되었습니다. 강의 등록 버튼을 눌러 강의를 등록하세요.', en: 'All required information has been entered. Click Submit to register your course.' },
  // 파일 업로드 모달
  fileUploadModalTitle: { ko: '파일 업로드', en: 'File Upload' },
  fileUploadModalDesc: { ko: '업로드할 파일을 선택하세요', en: 'Select a file to upload' },
  dragDropText: { ko: '파일을 드래그하거나 클릭하여 선택하세요', en: 'Drag and drop or click to select a file' },
  uploading: { ko: '업로드 중...', en: 'Uploading...' },
  uploadComplete: { ko: '업로드 완료', en: 'Upload Complete' },
  uploadError: { ko: '업로드 실패', en: 'Upload Failed' },
  upload: { ko: '업로드', en: 'Upload' },
  // 외부 링크 모달
  externalLinkModalTitle: { ko: '외부 링크 추가', en: 'Add External Link' },
  contentName: { ko: '콘텐츠 이름', en: 'Content Name' },
  contentNamePlaceholder: { ko: '콘텐츠 이름을 입력하세요', en: 'Enter content name' },
  urlInputLabel: { ko: 'URL', en: 'URL' },
  urlInputPlaceholder: { ko: 'https://example.com', en: 'https://example.com' },
  invalidUrl: { ko: '유효한 URL을 입력하세요', en: 'Please enter a valid URL' },
  add: { ko: '추가', en: 'Add' },
  // 기존 콘텐츠 모달
  existingContentModalTitle: { ko: '기존 콘텐츠 불러오기', en: 'Load Existing Content' },
  searchContent: { ko: '콘텐츠 검색', en: 'Search Content' },
  searchContentPlaceholder: { ko: '콘텐츠 이름으로 검색', en: 'Search by content name' },
  filterByType: { ko: '타입 필터', en: 'Filter by Type' },
  allTypes: { ko: '전체', en: 'All' },
  video: { ko: '비디오', en: 'Video' },
  audio: { ko: '오디오', en: 'Audio' },
  document: { ko: '문서', en: 'Document' },
  image: { ko: '이미지', en: 'Image' },
  noContentFound: { ko: '콘텐츠가 없습니다', en: 'No content found' },
  select: { ko: '선택', en: 'Select' },
  existingContent: { ko: '기존 콘텐츠', en: 'Existing Content' },
  // 콘텐츠 표시 정보
  contentDisplayName: { ko: '강의 내 표시 이름', en: 'Display Name in Course' },
  contentDisplayNamePlaceholder: { ko: '강의에서 표시할 이름 (미입력 시 원본 이름 사용)', en: 'Name to display in course (uses original name if empty)' },
  contentDescription: { ko: '강의 내 설명', en: 'Description in Course' },
  contentDescriptionPlaceholder: { ko: '강의에서 표시할 설명', en: 'Description to display in course' },
  // 공통
  cancel: { ko: '취소', en: 'Cancel' },
  processing: { ko: '처리 중...', en: 'Processing...' },
  // 작성완료 (DRAFT → READY)
  completeWriting: { ko: '작성완료', en: 'Complete' },
  completing: { ko: '작성완료 처리 중...', en: 'Completing...' },
  completeSuccess: { ko: '작성완료 되었습니다. 추후 리스트에서 등록할 수 있습니다.', en: 'Course marked as complete. You can register it later from the list.' },
  completeError: { ko: '작성완료 처리에 실패했습니다. 다시 시도해주세요.', en: 'Failed to mark as complete. Please try again.' },
  completeConfirm: { ko: '작성완료 하시겠습니까? 완료 후에도 수정이 가능합니다.', en: 'Mark as complete? You can still edit it later.' },
  // 등록 (READY → REGISTERED)
  register: { ko: '과정 등록', en: 'Register Course' },
  registering: { ko: '과정 등록 중...', en: 'Registering Course...' },
  registerSuccess: { ko: '등록되었습니다. 운영자가 차수를 개설할 수 있습니다.', en: 'Course has been registered. Operators can now create sessions.' },
  registerError: { ko: '등록에 실패했습니다. 다시 시도해주세요.', en: 'Failed to register. Please try again.' },
  registerConfirm: { ko: '등록하시겠습니까? 등록 후에는 운영자가 차수를 개설할 수 있습니다.', en: 'Register this course? After registration, operators can create course sessions.' },
  // 발행 (deprecated)
  publish: { ko: '발행하기', en: 'Publish' },
  publishing: { ko: '발행 중...', en: 'Publishing...' },
  publishSuccess: { ko: '강의가 발행되었습니다.', en: 'Course has been published.' },
  publishError: { ko: '발행에 실패했습니다. 다시 시도해주세요.', en: 'Failed to publish. Please try again.' },
  publishConfirm: { ko: '강의를 발행하시겠습니까? 발행 후에는 과정에 신청할 수 있습니다.', en: 'Do you want to publish this course? After publishing, you can apply for programs.' },
  readyToPublish: { ko: '발행 준비 완료', en: 'Ready to Publish' },
  readyToPublishDesc: { ko: '모든 필수 정보가 입력되었습니다. 발행하기 버튼을 눌러 강의를 발행하세요.', en: 'All required information has been entered. Click Publish to publish your course.' },
  // 페이지네이션
  prev: { ko: '이전', en: 'Prev' },
  pageInfo: { ko: '{current} / {total} 페이지', en: 'Page {current} of {total}' },
  // 미리보기
  preview: { ko: '미리보기', en: 'Preview' },
  previewTitle: { ko: '강의 미리보기', en: 'Course Preview' },
  previewDesc: { ko: '수강생이 보게 될 강의 모습입니다.', en: 'This is how learners will see this course.' },
  previewMode: { ko: '미리보기 모드', en: 'Preview Mode' },
  closePreview: { ko: '미리보기 닫기', en: 'Close Preview' },
  noPreviewData: { ko: '미리보기 데이터가 없습니다.', en: 'No preview data available.' },
} as const;

export type TranslationKey = keyof typeof translations;

export const levelOptions = [
  { value: '', label: '난이도 선택' },
  { value: 'BEGINNER', label: '초급' },
  { value: 'INTERMEDIATE', label: '중급' },
  { value: 'ADVANCED', label: '고급' },
];

export const typeOptions = [
  { value: '', label: '유형 선택' },
  { value: 'ONLINE', label: '온라인' },
  { value: 'OFFLINE', label: '오프라인' },
  { value: 'BLENDED', label: '블렌디드' },
];
