name: Feature Request
description: 새로운 기능 요청
title: "[Feat] "
labels: ["feat"]
body:
  - type: textarea
    id: description
    attributes:
      label: 설명
      description: 구현할 기능에 대해 설명해주세요.
      placeholder: JWT 기반 로그인/로그아웃 API 구현
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 내용
      description: 세부 작업 목록을 작성해주세요.
      placeholder: |
        - [ ] Entity 설계
        - [ ] DTO 생성
        - [ ] Service 구현
        - [ ] Controller 구현
        - [ ] 테스트 코드 작성
    validations:
      required: true

  - type: textarea
    id: api-spec
    attributes:
      label: API 스펙 (선택)
      description: API 엔드포인트가 있다면 작성해주세요.
      placeholder: |
        ```
        POST /api/auth/login
        Request: { email, password }
        Response: { accessToken, refreshToken }
        ```
    validations:
      required: false

  - type: input
    id: branch
    attributes:
      label: 관련 브랜치
      description: 작업할 브랜치명을 입력해주세요.
      placeholder: feat/user-login
    validations:
      required: false
